# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bbcnews',
            fields=[
                ('title', models.CharField(blank=True, db_column='title', max_length=100)),
                ('url', models.CharField(blank=True, db_column='url', max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
            ],
            options={
                'db_table': 'bbcnews',
                'managed': False,
            },
        ),
    ]
